name: Build ThunderOnWindows

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
 
env:
  devEnv: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  solution: Thunder.sln

jobs:
  ThunderOnWindows:
    runs-on: windows-latest

    strategy:
      matrix:
        type: [Debug, Release]
        version: [64, 86]

# ----- Checkout -----
    name: Build type - ${{matrix.type}}${{matrix.version}}
    steps:
    - name: Checkout ThunderOnWindows
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows
        repository: WebPlatformForEmbedded/ThunderOnWindows

    - name: Checkout Thunder
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/Thunder
        repository: rdkcentral/Thunder

    - name: Checkout ThunderTools
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/ThunderTools
        repository: rdkcentral/ThunderTools

    - name: Checkout ThunderClientLibraries
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/ThunderClientLibraries
        repository: rdkcentral/ThunderClientLibraries

    - name: Checkout ThunderInterfaces
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/ThunderInterfaces
        repository: rdkcentral/ThunderInterfaces

    - name: Checkout ThunderNanoServices
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/ThunderNanoServices
        repository: rdkcentral/ThunderNanoServices

    - name: Checkout ThunderNanoServicesRDK
      uses: actions/checkout@v4
      with:
        path: ThunderOnWindows/ThunderNanoServicesRDK
        repository: WebPlatformForEmbedded/ThunderNanoServicesRDK

# ----- Install & Build -----
    - name: Install jsonref
      run: pip install jsonref

    - name: Build ThunderOnWindows
      shell: cmd
      run: |
        cd ThunderOnWindows
        "%devEnv%" /Build "${{matrix.type}}|x${{matrix.version}}"  "%solution%"
        mkdir ..\artifacts\Debug
        mkdir ..\artifacts\Persistent
        mkdir ..\artifacts\temp\MessageDispatcher
        move lib\static_x64\libcrypto-1_1-x64.dll ..\artifacts\Debug\libcrypto-1_1-x64.dll
        move lib\static_x64\libssl-1_1-x64.dll ..\artifacts\Debug\libssl-1_1-x64.dll
        robocopy ThunderUI\dist ..\artifacts\Debug\Plugins\Controller\UI /S
        
    
    - name: Add ms-build
      uses: microsoft/setup-msbuild@v2
      
    - name: Build app for release
      run: msbuild Thunder.sln -t:rebuild -verbosity:diag -property:Configuration=Release -p:AdditionalConfigFile="ExampleConfigWindows.json"

    - name: Run Image
      run: dotnet build --no-build


